core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    # path('store/all_product', views.all_products, name='all_products'),
    path('store/', views.search_products, name='search_products'),
    path('store/category/<slug:slug>/', views.category_products, name='category_products'),
    path('detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('update_item/', views.update_item, name='update_item'),
    path('cart/', views.cart, name='cart'),
    path('place_order/', views.place_order, name='place_order'),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Customer


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    created_by = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created', )

    def __str__(self):
        return self.title


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f'{self.customer.first_name} {self.customer.last_name}'

    @property
    def get_total_items(self):
        order_items = self.order_items.all()
        total = sum([item.quantity for item in order_items])
        return total

    @property
    def get_total_prices(self):
        order_items = self.order_items.all()
        total = sum([item.get_price for item in order_items])
        return total

    @property
    def get_tax(self):
        return self.get_total_prices * 3 / 100

    @property
    def get_prices_with_tax(self):
        return self.get_total_prices + self.get_tax


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True, related_name='order_items')
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title

    @property
    def get_price(self):
        return self.product.price * self.quantity


class Delivery(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    street = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    is_complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.street


PAYMENT_STATUS_CHOICES = (
    ('pending', 'Pending'),
    ('completed', 'Completed'),
    ('failed', 'Failed'),
)


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=256)
    status = models.CharField(max_length=10, choices=PAYMENT_STATUS_CHOICES)
    payer_id = models.CharField(max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.payment_id

store/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.db.models import Q

from .models import Category, Product, Customer, Order, OrderItem


def home(request):
    products = Product.objects.all().order_by('-created')[:8]
    context = {'products': products}
    return render(request, 'store/index.html', context)


def search_products(request):
    query = request.GET.get('q')
    min_price = request.GET.get('min')
    max_price = request.GET.get('max')
    if query is not None:
        products = Product.objects.filter(title__icontains=query)
    elif min_price and max_price is not None:
        products = Product.objects.filter(Q(price__gte=min_price) & Q(price__lte=max_price))
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    if page is None:
        page = 1
    items = paginator.get_page(page)
    context = {
        'products': items,
        'query': query
    }
    return render(request, 'store/store.html', context)


def products_price_range(request):
    pass


# def all_products(request):
#     products = Product.objects.all().order_by('-created')
#     context = {'products': products}
#     return render(request, 'store/store.html', context)


def category_products(request, slug):
    category = Category.objects.get(slug=slug)
    products = category.products.all()
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    if page is None:
        page = 1
    items = paginator.get_page(page)
    context = {
        'category': category,
        'products': items
    }
    return render(request, 'store/store.html', context)


def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    context = {'product': product}
    return render(request, 'store/product-detail.html', context)


@login_required(login_url='/accounts/login/')
def cart(request):
    customer = request.user.customer
    order = Order.objects.get(customer=customer)

    context = {
        'items': order.order_items.all(),
        'order': order
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='/login/')
def place_order(request):
    customer = request.user.customer
    order = Order.objects.get(customer=customer)

    context = {
        'items': order.order_items.all(),
        'order': order
    }
    return render(request, 'store/place-order.html', context)


@csrf_exempt
def update_item(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        product_id = data['productId']
        action = data['action']
        customer = request.user.customer
        product = Product.objects.get(id=product_id)
        order, created = Order.objects.get_or_create(customer=customer)
        order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

        if action == 'add':
            order_item.quantity += 1
        elif action == 'minus':
            order_item.quantity -= 1
        elif action == 'remove':
            order_item.quantity = 0

        order.save()
        order_item.save()

        if order_item.quantity <= 0:
            order_item.delete()

    return JsonResponse('item was added', safe=False)

templates/store/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}GreatKart | One of the Biggest Online Shopping Platform{% endblock %}</title>

    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>


    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
        // jquery end
    </script>
    <script>
        const user = '{{ request.user }}'
    </script>
</head>
<body>


<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> English </a>

                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> USD </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'store:home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                                <a class="dropdown-item" href="{% url 'store:category_products' category.slug %}">{{ category.name }} </a>

                            {% endfor %}

                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'store:search_products' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'store:search_products' %}" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="q">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            {% if user.is_authenticated %}
                                <small class="title text-muted">{{ user.customer.last_name }}!</small>
                            {% else %}
                                <small class="title text-muted">Welcome guest!</small>
                            {% endif %}

                            <div>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'user_logout' %}"> Logout</a>
                                {% else %}
                                    <a href="{% url 'user_login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'user_register' %}"> Register</a>
                                {% endif %}
                            </div>
                        </div>
                        <a href="{% url 'store:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ items_count }}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->


</header> <!-- section-header.// -->


{% block content %}

{% endblock %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
    <div class="container">
        <section class="footer-bottom border-top row">
            <div class="col-md-2">
                <p class="text-muted"> &copy 2019 Company name </p>
            </div>
            <div class="col-md-8 text-md-center">
                <span class="px-2">info@pixsellz.io</span>
                <span class="px-2">+879-332-9375</span>
                <span class="px-2">Street name 123, Avanue abc</span>
            </div>
            <div class="col-md-2 text-md-right text-muted">
                <i class="fab fa-lg fa-cc-visa"></i>
                <i class="fab fa-lg fa-cc-paypal"></i>
                <i class="fab fa-lg fa-cc-mastercard"></i>
            </div>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

templates/store/cart.html
{% extends 'store/base.html' %}

{% block title %}
    cart
{% endblock %}



{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->

            <div class="row">
                <aside class="col-lg-9">
                    <div class="card">
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in items %}
                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside"><img src="{{ item.product.image.url }}" class="img-sm">
                                            </div>
                                            <figcaption class="info">
                                                <a href="#" class="title text-dark">{{ item.product.title }}</a>

                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <!-- col.// -->
                                        <div class="col">
                                            <div class="input-group input-spinner">
                                                <div class="input-group-prepend">
                                                    <button class="btn btn-light update-cart" type="button" id="button-plus"
                                                            data-action="minus" data-product="{{ item.product_id }}"
                                                            href="{% url 'store:update_item' %}">
                                                        <i
                                                                class="fa fa-minus"></i></button>
                                                </div>
                                                <input type="text" class="form-control" value="{{ item.quantity }}">
                                                <div class="input-group-append">
                                                    <button class="btn btn-light update-cart" type="button" id="button-minus"
                                                            data-action="add" data-product="{{ item.product_id }}"
                                                            href="{% url 'store:update_item' %}">
                                                        <i
                                                                class="fa fa-plus"></i></button>
                                                </div>
                                            </div> <!-- input-group.// -->
                                        </div> <!-- col.// -->
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price">${{ item.product.price }}</var>
                                            {#                                            <small class="text-muted"> ${{ item.price }} </small>#}
                                        </div> <!-- price-wrap .// -->
                                    </td>
                                    <td class="text-right">
                                        <button href="{% url 'store:update_item' %}" class="btn btn-danger update-cart" data-action="remove" data-product="{{ item.product_id }}"> Remove</button>
                                    </td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <aside class="col-lg-3">

                    <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                                <dt>Total price:</dt>
                                <dd class="text-right">${{ order.get_total_prices }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Tax:</dt>
                                <dd class="text-right"> ${{ order.get_tax }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Total:</dt>
                                <dd class="text-right text-dark b"><strong>${{ order.get_prices_with_tax }}</strong></dd>
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                {% load static %}
                                <img src="{% static 'images/misc/payments.png' %}" height="26">
                            </p>
                            <a href="{% url 'store:place_order' %}" class="btn btn-primary btn-block"> Checkout </a>
                            <a href="{% url 'store:search_products' %}" class="btn btn-light btn-block">Continue Shopping</a>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->


            </div> <!-- row.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>
    {% load static %}
    <script src="{% static 'js/updateItem.js' %}" type="text/javascript">

    </script>
{% endblock %}

templates/store/store.html
{% extends 'store/base.html' %}

{% block title %}

{% endblock %}


{% block content %}
    <section class="section-content padding-y">
        <div class="container">

            <div class="row">
                <aside class="col-md-3">

                    <div class="card">
                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Categories</h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_1" style="">
                                <div class="card-body">

                                    <ul class="list-menu">
                                        {% for category in categories %}
                                            <li>
                                                <a href="{% url 'store:category_products' category.slug %}">{{ category.name }} </a>
                                            </li>
                                        {% endfor %}
                                    </ul>

                                </div> <!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group  .// -->

                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Price range </h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_3" style="">
                                <form method="GET" action="{% url 'store:search_products' %}">
                                    <div class="card-body">

                                        <div class="form-row">

                                            <div class="form-group col-md-6">
                                                <label>Min</label>
                                                <!-- <input class="form-control" placeholder="$0" type="number"> -->
                                                <select class="mr-2 form-control" name="min">
                                                    <option value="0">$0</option>
                                                    <option value="50">$50</option>
                                                    <option value="100">$100</option>
                                                    <option value="150">$150</option>
                                                    <option value="200">$200</option>
                                                    <option value="500">$500</option>
                                                    <option value="1000">$1000</option>
                                                </select>
                                            </div>
                                            <div class="form-group text-right col-md-6">
                                                <label>Max</label>
                                                <select class="mr-2 form-control" name="max">
                                                    <option value="50">$50</option>
                                                    <option value="100">$100</option>
                                                    <option value="150">$150</option>
                                                    <option value="200">$200</option>
                                                    <option value="500">$500</option>
                                                    <option value="1000">$1000</option>
                                                    <option value="2000">$2000+</option>
                                                </select>
                                            </div>

                                        </div> <!-- form-row.// -->
                                        <button class="btn btn-block btn-primary">Apply</button>
                                    </div><!-- card-body.// -->
                                </form>
                            </div>
                        </article> <!-- filter-group .// -->

                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <main class="col-md-9">

                    <header class="border-bottom mb-4 pb-3">
                        <div class="form-inline">
                            <span class="mr-md-auto">{{ products.count }} Items found </span>

                        </div>
                    </header><!-- sect-heading -->

                    <div class="row">
                        {% for product in products %}
                            <div class="col-md-4">
                                <figure class="card card-product-grid">
                                    <div class="img-wrap">

                                        <img src="{{ product.image.url }}">

                                    </div> <!-- img-wrap.// -->
                                    <figcaption class="info-wrap">
                                        <div class="fix-height">
                                            <a href="{% url 'store:product_detail' product.slug %}"
                                               class="title">{{ product.title }}</a>
                                            <div class="price-wrap mt-2">
                                                <span class="price">${{ product.price }}</span>
                                                {#<del class="price-old">$1980</del>#}
                                            </div> <!-- price-wrap.// -->
                                        </div>
                                        <button href="{% url 'store:update_item' %}"
                                                class="btn btn-block btn-success update-cart"
                                                data-product="{{ product.id }}" data-action="add">Added to cart
                                        </button>
                                    </figcaption>
                                </figure>
                            </div> <!-- col.// -->
                        {% endfor %}


                    </div> <!-- row end.// -->


                    <nav class="mt-4" aria-label="Page navigation sample">
                        <ul class="pagination">
                            {% if products.has_previous %}

                                <li class="page-item"><a class="page-link"
                                                         href="?{% if query %}q={{ query }}&{% endif %}page={{ products.previous_page_number }}">Previous</a>
                                </li>
                            {% endif %}

                            {% for page in products.paginator.page_range %}
                                {% if products.number == page %}
                                    <li class="page-item active"><a class="page-link"
                                                                    href="?{% if query %}q={{ query }}&{% endif %}page={{ page }}">{{ page }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?{% if query %}q={{ query }}&{% endif %}page={{ page }}">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next %}
                                <li class="page-item"><a class="page-link"
                                                         href="?{% if query %}q={{ query }}&{% endif %}page={{ products.next_page_number }}">Next</a>
                                </li>
                            {% endif %}

                        </ul>
                    </nav>

                </main> <!-- col.// -->

            </div>

        </div> <!-- container .//  -->
    </section>
    {% load static %}
    <script src="{% static 'js/updateItem.js' %}" type="text/javascript">

    </script>
{% endblock %}